service: sls-demo
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
  greet:
    handler: src/jobs/greet.sayHello
  list:
    handler: src/jobs/showList.handler
    events:
      - http:
           method: GET
           path: /posts
  createList:
    handler: src/jobs/createList.handler
    events:
      - http:
           method: POST
           path: /posts
